export enum RootScreens {
  MAIN = "Main",
  START = "Start",
  WELCOME = "Welcome",
  ONBOARDING = "Onboarding",
  LOGIN = "Login",
  REGISTER = "Register",
  FORGOT_PASSWORD = "ForgotPassword",
  HOME = "Home",
  STUDY = "Study",
  FORUM = "Forum",
  CHAT = "Chat",
  PROFILE = "Profile",
  EDIT_PROFILE = "EditProfile",
  SETTINGS = "Settings",
}
